DROP TABLE IF EXISTS R_M,spparts,DEVICES,TEC,CLIENT;
CREATE TABLE CLIENT(CLIENT_cid INT,CLIENT_name VARCHAR(20),CLIENT_add VARCHAR(20),
CLIENT_tel INT );
CREATE TABLE DEVICES(DEVICES_did INT,DEVICES_name VARCHAR(10),DEVICES_tybe VARCHAR(20),
DEVICES_cid INT,DEVICES_sdate date );
CREATE TABLE SPPARTS(SPPARTS_sid INT,SPPARTS_name VARCHAR(10),SPPARTS_price INT,
SPPARTS_did INT,SPPARTS_indate date );
CREATE TABLE R_M(R_M_did INT,R_M_tecid INT,R_M_rdata DATE);
CREATE TABLE TEC(TEC_tecid INT,TEC_name VARCHAR(10),TEC_add VARCHAR(20),TEC_tel INT );

INSERT INTO CLIENT(CLIENT_cid ,CLIENT_name ,CLIENT_tel,CLIENT_add )
VALUES(1,'Malak Mohamed',01002345432,'EL Senbellawein');
INSERT INTO DEVICES(DEVICES_name ,DEVICES_tybe,DEVICES_sdate)
VALUES('Samsung','Broken Screen','06/06/2026');
INSERT INTO SPPARTS(SPPARTS_price)
VALUES(500);
INSERT INTO R_M(R_M_rdata)
VALUES('09/06/2026');
INSERT INTO TEC(TEC_name,TEC_tel)
VALUES('Eng.Ahmed',01535217954);

DROP TABLE DEVICES;

ALTER TABLE TEC
ALTER COLUMN TEC_add VARCHAR(30);